name: VDR Creation

on:
  workflow_dispatch:
    branches: [ main,  ]
  push:
    branches: [ main ]
  pull_request: # todo: do we want it to run on all PRs?
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

    - name: Set up Python 3.10
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Download ojvg
      run: |
        mkdir -p data
        python3 ojvg_download.py
        python3 ojvg_convert.py
    - name: Upload data directory
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 #v4.3.3
      with:
        name: data directory
        path: data
